#!/bin/bash

# REMEMBER TO CHANGE THIS VERSION #!!!!!!

WOODSTOCK_VERSION="4.0.2.10"

#================  webui-jsf jars  =====================
#

sed -e s/WOODSTOCK_VERSION/$WOODSTOCK_VERSION/ ./webui/webui.pom >  ./webui-jsf-$WOODSTOCK_VERSION.pom

cp ./master/build/ship/lib/webui-jsf.jar  ./webui-jsf-$WOODSTOCK_VERSION.jar

rm -rf tmp__1; mkdir tmp__1; cd tmp__1
unzip ../webui/dist/webui-jsf-doc.zip
jar cf ../webui-jsf-$WOODSTOCK_VERSION-javadoc.jar *
cd ..

rm -rf tmp__2; mkdir tmp__2; cd tmp__2
unzip ../webui/dist/webui-jsf-src.zip
jar cf ../webui-jsf-$WOODSTOCK_VERSION-sources.jar *
cd ..

rm -rf tmp__1 tmp__2

gpg -ab webui-jsf-$WOODSTOCK_VERSION.pom
gpg -ab webui-jsf-$WOODSTOCK_VERSION.jar
gpg -ab webui-jsf-$WOODSTOCK_VERSION-javadoc.jar
gpg -ab webui-jsf-$WOODSTOCK_VERSION-sources.jar

rm -rf webui-jsf-bundle.jar

jar -vcf webui-jsf-bundle.jar \
   webui-jsf-$WOODSTOCK_VERSION.pom webui-jsf-$WOODSTOCK_VERSION.pom.asc \
   webui-jsf-$WOODSTOCK_VERSION.jar webui-jsf-$WOODSTOCK_VERSION.jar.asc \
   webui-jsf-$WOODSTOCK_VERSION-javadoc.jar webui-jsf-$WOODSTOCK_VERSION-javadoc.jar.asc \
   webui-jsf-$WOODSTOCK_VERSION-sources.jar webui-jsf-$WOODSTOCK_VERSION-sources.jar.asc

#================  webui-jsf-suntheme jars =====================

sed -e s/WOODSTOCK_VERSION/$WOODSTOCK_VERSION/  ./themes/webui-jsf-suntheme.pom >  ./webui-jsf-suntheme-$WOODSTOCK_VERSION.pom

cp ./master/build/ship/lib/webui-jsf-suntheme.jar  ./webui-jsf-suntheme-$WOODSTOCK_VERSION.jar
cp ./master/build/ship/lib/webui-jsf-suntheme.jar  ./webui-jsf-suntheme-$WOODSTOCK_VERSION-sources.jar
cp ./themes/webui-jsf-suntheme-javadoc.jar ./webui-jsf-suntheme-$WOODSTOCK_VERSION-javadoc.jar

gpg -ab webui-jsf-suntheme-$WOODSTOCK_VERSION.pom
gpg -ab webui-jsf-suntheme-$WOODSTOCK_VERSION.jar
gpg -ab webui-jsf-suntheme-$WOODSTOCK_VERSION-javadoc.jar
gpg -ab webui-jsf-suntheme-$WOODSTOCK_VERSION-sources.jar

rm -rf webui-jsf-suntheme-bundle.jar

jar -vcf webui-jsf-suntheme-bundle.jar \
   webui-jsf-suntheme-$WOODSTOCK_VERSION.pom webui-jsf-suntheme-$WOODSTOCK_VERSION.pom.asc \
   webui-jsf-suntheme-$WOODSTOCK_VERSION.jar webui-jsf-suntheme-$WOODSTOCK_VERSION.jar.asc \
   webui-jsf-suntheme-$WOODSTOCK_VERSION-javadoc.jar webui-jsf-suntheme-$WOODSTOCK_VERSION-javadoc.jar.asc \
   webui-jsf-suntheme-$WOODSTOCK_VERSION-sources.jar webui-jsf-suntheme-$WOODSTOCK_VERSION-sources.jar.asc


###################################################################################
# Push the jars to maven repository.

#================  webui-jsf jars  =====================

#mvn gpg:sign-and-deploy-file -Dpassphrase=glassfish -Durl=https://maven.java.net/service/local/staging/deploy/maven2/ -DrepositoryId=jvnet-nexus-staging -DpomFile=webui-jsf-$WOODSTOCK_VERSION.pom -Dfile=webui-jsf-$WOODSTOCK_VERSION.jar

#mvn gpg:sign-and-deploy-file -Dpassphrase=glassfish -Durl=https://maven.java.net/service/local/staging/deploy/maven2/ -DrepositoryId=jvnet-nexus-staging -DpomFile=webui-jsf-$WOODSTOCK_VERSION.pom -Dfile=webui-jsf-$WOODSTOCK_VERSION-sources.jar -Dclassifier=sources

#mvn gpg:sign-and-deploy-file -Dpassphrase=glassfish -Durl=https://maven.java.net/service/local/staging/deploy/maven2/ -DrepositoryId=jvnet-nexus-staging -DpomFile=webui-jsf-$WOODSTOCK_VERSION.pom -Dfile=webui-jsf-$WOODSTOCK_VERSION-javadoc.jar -Dclassifier=javadoc


#================  webui-jsf-suntheme =====================

#echo "mvn gpg:sign-and-deploy-file -Dpassphrase=glassfish -Durl=https://maven.java.net/service/local/staging/deploy/maven2/ -DrepositoryId=jvnet-nexus-staging -DpomFile=webui-jsf-suntheme-$WOODSTOCK_VERSION.pom -Dfile=webui-jsf-suntheme-$WOODSTOCK_VERSION.jar"
#mvn gpg:sign-and-deploy-file -Dpassphrase=glassfish -Durl=https://maven.java.net/service/local/staging/deploy/maven2/ -DrepositoryId=jvnet-nexus-staging -DpomFile=webui-jsf-suntheme-$WOODSTOCK_VERSION.pom -Dfile=webui-jsf-suntheme-$WOODSTOCK_VERSION.jar

#echo "mvn gpg:sign-and-deploy-file -Dpassphrase=glassfish -Durl=https://maven.java.net/service/local/staging/deploy/maven2/ -DrepositoryId=jvnet-nexus-staging -DpomFile=webui-jsf-suntheme-$WOODSTOCK_VERSION.pom -Dfile=webui-jsf-$WOODSTOCK_VERSION.jar -Dclassifier=sources"
#mvn gpg:sign-and-deploy-file -Dpassphrase=glassfish -Durl=https://maven.java.net/service/local/staging/deploy/maven2/ -DrepositoryId=jvnet-nexus-staging -DpomFile=webui-jsf-suntheme-$WOODSTOCK_VERSION.pom -Dfile=webui-jsf-$WOODSTOCK_VERSION.jar -Dclassifier=sources

#echo "mvn gpg:sign-and-deploy-file -Dpassphrase=glassfish -Durl=https://maven.java.net/service/local/staging/deploy/maven2/ -DrepositoryId=jvnet-nexus-staging -DpomFile=webui-jsf-suntheme-$WOODSTOCK_VERSION.pom -Dfile=webui-jsf-$WOODSTOCK_VERSION-javadoc.jar -Dclassifier=javadoc"
#mvn gpg:sign-and-deploy-file -Dpassphrase=glassfish -Durl=https://maven.java.net/service/local/staging/deploy/maven2/ -DrepositoryId=jvnet-nexus-staging -DpomFile=webui-jsf-suntheme-$WOODSTOCK_VERSION.pom -Dfile=webui-jsf-$WOODSTOCK_VERSION-javadoc.jar -Dclassifier=javadoc


