#!/bin/bash

# REMEMBER TO CHANGE THIS VERSION #!!!!!!
WOODSTOCK_VER="4.0.2.5"

mvn install:install-file -Dfile=webui/netbeans/modules/autoload/ext/webui-jsf.jar \
                         -Dsources=webui/dist/webui-jsf-src.zip\
                         -Djavadoc=webui/dist/webui-jsf-doc.zip \
                         -DgroupId=com.sun.woodstock \
                         -DartifactId=webui-jsf \
                         -Dversion=$WOODSTOCK_VER \
                         -Dpackaging=jar

mvn install:install-file -Dfile=themes/dist/webui-jsf-suntheme.jar \
                         -DgroupId=com.sun.woodstock \
                         -DartifactId=webui-jsf-suntheme \
                         -Dversion=$WOODSTOCK_VER \
                         -Dpackaging=jar

mvn install:install-file -Dfile=webui/lib/external/json.jar \
                         -DgroupId=com.sun.woodstock.dependlibs \
                         -DartifactId=json \
                         -Dversion=1.0 \
                         -Dpackaging=jar

mvn install:install-file -Dfile=webui/lib/external/dojo-0.4.1-ajax.jar \
                         -DgroupId=com.sun.woodstock.dependlibs \
                         -DartifactId=dojo-ajax \
                         -Dversion=0.4.1 \
                         -Dpackaging=jar

mvn install:install-file -Dfile=webui/lib/external/prototype-1.5.0.jar \
                         -DgroupId=com.sun.woodstock.dependlibs \
                         -DartifactId=prototype \
                         -Dversion=1.5.0 \
                         -Dpackaging=jar
