#!/bin/sh
#
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# The contents of this file are subject to the terms of either the GNU
# General Public License Version 2 only ("GPL") or the Common Development
# and Distribution License("CDDL") (collectively, the "License").  You
# may not use this file except in compliance with the License.  You can
# obtain a copy of the License at
# https://oss.oracle.com/licenses/CDDL+GPL-1.1
# or LICENSE.txt.  See the License for the specific
# language governing permissions and limitations under the License.
#
# When distributing the software, include this License Header Notice in each
# file and include the License file at LICENSE.txt.
#
# GPL Classpath Exception:
# Oracle designates this particular file as subject to the "Classpath"
# exception as provided by Oracle in the GPL Version 2 section of the License
# file that accompanied this code.
#
# Modifications:
# If applicable, add the following below the License Header, with the fields
# enclosed by brackets [] replaced by your own identifying information:
# "Portions Copyright [year] [name of copyright owner]"
#
# Contributor(s):
# If you wish your version of this file to be governed by only the CDDL or
# only the GPL Version 2, indicate your decision by adding "[Contributor]
# elects to include this software in this distribution under the [CDDL or GPL
# Version 2] license."  If you don't indicate a single choice of license, a
# recipient has the option to distribute your version of this file under
# either the CDDL, the GPL Version 2 or to extend the choice of license to
# its licensees as provided above.  However, if you add GPL Version 2 code
# and therefore, elected the GPL Version 2 license, then the option applies
# only if the new code is made subject to such option by the copyright
# holder.
#

# This is tricky
# "ui:" is found in many places in the documentation on the conf files.
# It is defined in the renderer conf files by the taglib-prefix.
# Make this an entity.
# Need to find out how it is passed to the tld generator.
# It looks like the "-p ui" option. These args are ant properties
# defined in webui/build.properties

newmodule="woodstock"
tagprefix="webuijsf"
#taguri="http://jvnet.org/webui/${tagprefix}"
taguri="http://www.sun.com/webui/${tagprefix}"


### Fix up lockhart/example jsp's ###

cd $newmodule/lockhart/example/web
for f in `find . -name \*.jsp -print` ; do

    sed -e 's?ui="http://www.sun.com/web/ui"?'${tagprefix}'="'${taguri}'"?' \
	-e 's?uri="http://www.sun.com/web/ui"?uri="'${taguri}'"?' \
	-e 's?prefix="ui"?prefix="'${tagprefix}'"?' \
	-e 's?<ui:?<'${tagprefix}':?g' \
	-e 's?</ui:?</'${tagprefix}':?g' \
	-e 's?lt;ui:?lt;'${tagprefix}':?g' \
	-e 's?lt;/ui:?lt;/'${tagprefix}':?g' \
	-e 's? ui:? '${tagprefix}':?g' $f > /tmp/junk

    mv /tmp/junk $f

done
