//<!--
// The contents of this file are subject to the terms
// of the Common Development and Distribution License
// (the License).  You may not use this file except in
// compliance with the License.
// 
// You can obtain a copy of the license at
// https://woodstock.dev.java.net/public/CDDLv1.0.html.
// See the License for the specific language governing
// permissions and limitations under the License.
// 
// When distributing Covered Code, include this CDDL
// Header Notice in each file and include the License file
// at https://woodstock.dev.java.net/public/CDDLv1.0.html.
// If applicable, add the following below the CDDL Header,
// with the fields enclosed by brackets [] replaced by
// you own identifying information:
// "Portions Copyrighted [year] [name of copyright owner]"
// 
// Copyright 2008 Sun Microsystems, Inc. All rights reserved.
//

// Note: Do not use multiline comments below for TLD examples as renderer XML
// files shall be used to generate Javadoc. Embedding a "*/" in a Javadoc 
// comment cuases compile errors because it terminates the outer comment.

// Toggle the filter panel from the filter menu.
//
// If the "Custom Filter" option has been selected, the filter panel is 
// toggled. In this scenario, false is returned indicating the onChange event,
// generated by the filter menu, should not be allowed to continue.
// 
// If the "Custom Filter Applied" option has been selected, no action is taken.
// Instead, the filter menu is reverted back to the original selection. In this
// scenario, false is also returned indicating the onChange event, generated by
// the filter menu, should not be allowed to continue.
//
// For all other selections, true is returned indicating the onChange event, 
// generated by the filter menu, should be allowed to continue.
function filterMenuChanged() {
    var table = document.getElementById("form1:table1");
    return table.filterMenuChanged();
}

// Use this function to toggle the filter panel open or closed. This
// functionality requires the filterId of the table component to be set. In 
// addition, the selected value must be set as well to restore the default
// selected value when the embedded filter panel is closed.
function toggleFilterPanel() {
    var table = document.getElementById("form1:table1");
    table.toggleFilterPanel();
}

//-->
