//<!--
// The contents of this file are subject to the terms
// of the Common Development and Distribution License
// (the License).  You may not use this file except in
// compliance with the License.
// 
// You can obtain a copy of the license at
// https://woodstock.dev.java.net/public/CDDLv1.0.html.
// See the License for the specific language governing
// permissions and limitations under the License.
// 
// When distributing Covered Code, include this CDDL
// Header Notice in each file and include the License file
// at https://woodstock.dev.java.net/public/CDDLv1.0.html.
// If applicable, add the following below the CDDL Header,
// with the fields enclosed by brackets [] replaced by
// you own identifying information:
// "Portions Copyrighted [year] [name of copyright owner]"
// 
// Copyright 2007 Sun Microsystems, Inc. All rights reserved.
//
// This Javascript file should be included in any page that uses the associated
// component, where JSF Extensions is used as the underlying transfer protocol.
//

dojo.provide("webui.@THEME@.widget.jsfx.progressBar");

dojo.require("webui.@THEME@.widget.progressBar");

/**
 * This name space is used to update data asynchronously.
 */
webui.@THEME@.widget.jsfx.progressBar =  {
    /**
     * This function is used to process progress events.
     *
     * @param evt Event generated by scroll bar.
     */
    processProgressEvent: function(id) {
        // Dynamic Faces requires a DOM node as the source property.
        var domNode = document.getElementById(id);

        // Generate AJAX request using the JSF Extensions library.
        new DynaFaces.fireAjaxTransaction(
            (domNode) ? domNode : document.forms[0], {
            execute: "none",
            render: id,
            replaceElement: webui.@THEME@.widget.jsfx.progressBar.update });

        return true;
    },

    /**
     * This function is used to update progress.
     *
     * @param elementId The HTML element Id.
     * @param content The content returned by the AJAX response.
     * @param closure The closure argument provided to DynaFaces.fireAjaxTransaction.
     * @param xjson The zjson argument provided to DynaFaces.fireAjaxTransaction.
     */
    update: function(elementId, content, closure, xjson) {
        if (elementId == null || content == null) {
            return false;
        }

        // Parse JSON text.
        var json = JSON.parse(content);

        // Set progress.
        var widget = dojo.widget.byId(elementId);
        widget.setProgress({
            failedStateText : json.failedStateText,
            logMessage : json.logMessage,
            progress : json.progress,
            status: json.status,
            taskState : json.taskState,
            topText : json.topText
        });

        // Publish an event for custom AJAX implementations to listen for.
        webui.@THEME@.widget.progressBar.progress.publishEndEvent(json);
        return true;
    }
}

// Listen for Dojo Widget events.
dojo.event.topic.subscribe(webui.@THEME@.widget.progressBar.progress.beginEventTopic,
    webui.@THEME@.widget.jsfx.progressBar, "processProgressEvent");

//-->
